#ifndef H_MASTER
 #define H_MASTER
#define STRICT
/*
#define STRICT
#include <windows.h>
#include <windowsx.h>
#include <commdlg.h>
#include <memory.h>
*/
#include <time.h>
//#include <vfw.h>


#include <owl\owlpch.h>
#include <owl\applicat.h>
#include <owl\framewin.h>
#include <owl\dc.h>
#include <owl\statusba.h>
#include <owl\controlb.h>
#include <owl\color.h>
#include <owl\chooseco.h>
#include <classlib\arrays.h>
#include <owl\radiobut.h>
#include <owl\groupbox.h>
#include <owl\dialog.h>
#include <owl\validate.h>
#include <owl\edit.h>
#include <classlib\objstrm.h>
#include <dir.h>
#include <owl\buttonga.h>
#include <owl\gadget.h>
#include <owl\listbox.h>
#include <owl\inputdia.h>
#include <owl\choosefo.h>
#include <owl\opensave.h>
#include <classlib\file.h>
#include <stdio.h>
#include <math.h>
#include <owl\combobox.h>
#include <owl\slider.h>
#include <owl\scroller.h>
#include <owl/oleframe.h>
#include <owl/olewindo.h>
#include <ocf/ocstorag.h>
#include <ocf/automacr.h>
#include <mmsystem.h>
#include <bwcc.h>
//#include <vfw.h>
#endif

