//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WorldConstructKit.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_WORLDCTYPE                  129
#define IDB_TREE_IMAGES                 130
#define IDD_WORLD                       131
#define IDD_MUSIC_SCRIPT                132
#define IDD_MUSIC_SAMPLE                133
#define IDD_CHARACTER_INFO              134
#define IDD_SCENE_DEFINITION            135
#define IDD_SKY_DEFINITION              136
#define IDD_ITEM_DEFINITION             137
#define IDD_CAMERA_DEFINITION           138
#define IDD_STAGING_INFO                139
#define IDD_IMAGE_INFO                  140
#define IDD_ANIMATION_INFO              141
#define IDD_CHARACTER_CONTEXT           142
#define IDD_SFX_INFO                    143
#define IDD_TEXT_DISPLAY                144
#define IDD_HOT_SPOT_INFO               145
#define IDD_KEYBOARD_TRIGGER            146
#define IDD_EMPTY_FORM                  153
#define IDD_NEW_NODE                    154
#define IDC_CLOCK_VALUE                 1004
#define IDC_SPIN_CLOCK_VALUE            1005
#define IDC_MUSIC_FILE_COUNT            1006
#define IDC_MUSIC_SCRIPT_COUNT          1008
#define IDC_CHARACTER_NUMBER            1010
#define IDC_SCENES_NUMBER               1012
#define IDC_SKY_NUMBER                  1014
#define IDC_INVENTORY_SIZE              1016
#define IDC_CAMERA_COUNT                1018
#define IDC_RECORD_COUNT                1020
#define IDC_COMBO_SKY_ID                1023
#define IDC_SCRIPT_ID                   1025
#define IDC_LOOP_END                    1028
#define IDC_COMBO_COMMAND_ARR           1030
#define IDC_COLOR_R_END                 1030
#define IDC_IS_WAIT_COMMAND_FINISH      1032
#define IDC_IS_OBEY_COMMAND             1035
#define IDC_FILE_NAME                   1037
#define IDC_END_SAMPLE                  1038
#define IDC_START_SAMPLE                1039
#define IDC_IS_SCENE_NAVIGABLE          1040
#define IDC_COMBO_MUSIC_SCRIPT          1041
#define IDC_TOP_REGION_END              1044
#define IDC_IS_DISPLAY_INVENTORY        1049
#define IDC_INVENTORY_LEFT              1050
#define IDC_INVENTORY_TOP               1051
#define IDC_INVENTORY_WIDTH             1052
#define IDC_INVENTORY_HEIGHT            1053
#define IDC_ACTIVE_TEXT                 1060
#define IDC_SKY_TOP                     1065
#define IDC_SKY_LEFT                    1066
#define IDC_SKY_HEIGHT                  1067
#define IDC_FRAME_COUNT                 1068
#define IDC_FRAME_CLOCK_INTERVAL        1070
#define IDC_COMBO_INTERATION_TYPE       1072
#define IDC_IS_INTERACTION_ENABLED      1073
#define IDC_IS_STASHED_ITEM             1075
#define IDC_SCENE_ID                    1076
#define IDC_IS_SCENE_INITIALIZED        1077
#define IDC_IS_APPLY_COLOR_FILTER       1078
#define IDC_SPIN_COLOR_H_START          1079
#define IDC_SPIN_COLOR_L_START          1080
#define IDC_COLOR_H_START               1081
#define IDC_COLOR_L_START               1082
#define IDC_COLOR_S_START               1083
#define IDC_SPIN_COLOR_S_START          1084
#define IDC_IS_APPLY_TRANSPARENCY       1085
#define IDC_TRANSPARENT_START           1086
#define IDC_SPIN_TRANSPARENT_START      1087
#define IDC_END_CLOCK_VALUE             1088
#define IDC_TRANSPARENCY_END            1089
#define IDC_SPIN_TRANSPARENCY_END       1090
#define IDC_IMAGE_FILE_NAME             1091
#define IDC_WIDTH_START                 1092
#define IDC_HEIGHT_START                1093
#define IDC_LEFT_START                  1094
#define IDC_COLOR_H_END                 1095
#define IDC_TOP_START                   1095
#define IDC_SPIN_COLOR_H_END            1096
#define IDC_WIDTH_END                   1096
#define IDC_COLOR_L_END                 1097
#define IDC_HEIGHT_END                  1097
#define IDC_SPIN_COLOR_L_END            1098
#define IDC_LEFT_END                    1098
#define IDC_COLOR_S_END                 1099
#define IDC_TOP_END                     1099
#define IDC_SPIN_COLOR_S_END            1100
#define IDC_ALPHA_FILE_NAME             1101
#define IDC_LEFT_ALPHA                  1102
#define IDC_TOP_ALPHA                   1103
#define IDC_MAP_FILE_NAME               1104
#define IDC_COLOR_COUNT                 1105
#define IDC_MAP_WIDTH                   1107
#define IDC_MAP_HEIGHT                  1108
#define IDC_MAP_LEFT                    1109
#define IDC_MAP_TOP                     1110
#define IDC_LIGHTING_MODE               1111
#define IDC_LIGHTING_FILE_NAME          1112
#define IDC_LIGHT_R                     1113
#define IDC_LIGHT_B                     1114
#define IDC_LIGHT_G                     1115
#define IDC_CAMERA_HEIGHT               1116
#define IDC_START_CLOCK_VALUE           1117
#define IDC_CAMERA_ANGLE                1117
#define IDC_LIGHT_ANGLE_X               1118
#define IDC_LIGHT_ANGLE_Y               1119
#define IDC_Z_END                       1120
#define IDC_LIGHT_ANGLE_Z               1120
#define IDC_CURRENT_FRAME               1122
#define IDC_FRAME_INTERVAL              1125
#define IDC_LOOP_REMAINING              1126
#define IDC_IS_IMAGE_VISIBLE            1129
#define IDC_ANIMATION_ID                1130
#define IDC_FILE_NAME_VIDEO             1131
#define IDC_FILE_NAME_AUDIO             1132
#define IDC_Z_START                     1133
#define IDC_START_FRAME                 1136
#define IDC_END_FRAME                   1137
#define IDC_VOLUME_START                1139
#define IDC_VOLUME_END                  1140
#define IDC_IS_DO_VIDEO                 1141
#define IDC_IS_DO_AUDIO                 1142
#define IDC_SFX_ID                      1143
#define IDC_START_POSITION              1144
#define IDC_END_POSTION                 1145
#define IDC_SPIN_VOLUME_START           1148
#define IDC_SPIN_VOLUME_END             1149
#define IDC_IS_AUDIO_ENABLED            1150
#define IDC_KEY_ID                      1151
#define IDC_KEY_CODE                    1152
#define IDC_IS_TRIGGER_ENABLED          1154
#define IDC_TEXT_ID                     1155
#define IDC_FONT_NAME                   1156
#define IDC_COMBO_TEXT_TYPE             1158
#define IDC_DISPLAY_STRING              1159
#define IDC_COLOR_G_START               1160
#define IDC_COLOR_B_START               1161
#define IDC_FONT_SIZE_START             1162
#define IDC_LEFT_REGION_START           1163
#define IDC_WIDTH_REGION_START          1164
#define IDC_HEIGHT_REGION_START         1165
#define IDC_COLOR_G_END                 1166
#define IDC_COLOR_B_END                 1167
#define IDC_FONT_SIZE_END               1168
#define IDC_COLOR_R_START               1169
#define IDC_LEFT_REGION_END             1170
#define IDC_WIDTH_REGION_END            1171
#define IDC_HEIGHT_REGION_END           1172
#define IDC_TOP_REGION_START            1173
#define IDC_IS_SHOW_TEXT                1174
#define IDC_HOT_SPOT_ID                 1175
#define IDC_COMBO_HOT_SPOT_MODE         1176
#define IDC_COMBO_IMAGE_ID              1177
#define IDC_COMBO_ANIMATION_ID          1178
#define IDC_COMBO_CHARACTER_ID          1179
#define IDC_LEFT_RECT                   1180
#define IDC_TOP_RECT                    1181
#define IDC_RIGHT_RECT                  1182
#define IDC_BOTTOM_RECT                 1183
#define IDC_FEEDBACK_STRING             1186
#define IDC_COMBO_INTERACTION_SUB_TYPE  1190
#define IDC_IS_TRANSFORM_CURSOR         1195
#define IDC_COMBO_LAYER                 1196
#define IDC_IS_FROZEN_CAMERA            1197
#define IDC_IS_CAMERA_ENABLED           1198
#define IDC_SPIN_COLOR_B_START          1199
#define IDC_SPIN_COLOR_G_START          1200
#define IDC_SPIN_COLOR_R_START          1201
#define IDC_SPIN_LEFT_REGION_START      1202
#define IDC_SPIN_TOP_REGION_START       1203
#define IDC_SPIN_WIDTH_REGION_START     1204
#define IDC_SPIN_HEIGHT_REGION_START    1205
#define IDC_SPIN_FONT_SIZE_START        1206
#define IDC_SPIN_COLOR_B_END            1207
#define IDC_SPIN_COLOR_G_END            1208
#define IDC_SPIN_COLOR_R_END            1209
#define IDC_SPIN_FONT_SIZE_END          1210
#define IDC_SPIN_LEFT_REGION_END        1211
#define IDC_SPIN_TOP_REGION_END         1212
#define IDC_SPIN_WIDTH_REGION_END       1213
#define IDC_SPIN_HEIGHT_REGION_END      1214
#define IDC_BROWSE                      1215
#define IDC_SKY_ID                      1216
#define IDC_SKY_FILE_NAME               1217
#define IDC_SKY_WIDTH                   1218
#define IDC_SPIN_SKY_WIDTH              1219
#define IDC_SPIN_SKY_HEIGHT             1220
#define IDC_SPIN_SKY_LEFT               1221
#define IDC_SPIN_SKY_TOP                1222
#define IDC_SPIN_FRAME_COUNT            1223
#define IDC_SPIN_CURRENT_FRAME          1224
#define IDC_SPIN_FRAME_CLOCK_INTERVAL   1225
#define IDC_SAMPLE_ID                   1226
#define IDC_MUSIC_SAMPLE_FILE_NAME      1227
#define IDC_LOOP_START                  1230
#define IDC_CURRENT_COMMAND             1231
#define IDC_REPEAT_COMMAND              1233
#define IDC_LIST_SAMPLE_ID              1234
#define IDC_SPIN_LOOP_START             1235
#define IDC_SPIN_LOOP_END               1236
#define IDC_SPIN_CURRENT_MUSIC          1237
#define IDC_SPIN_REPEAT_COMMAND         1238
#define IDC_EDIT_MUSIC                  1239
#define IDC_DELETE_MUSIC                1240
#define IDC_ADD_MUSIC                   1241
#define IDC_ITEM_ID                     1242
#define IDC_BROWSE_AUDIO_FILE_NAME      1255
#define IDC_BROWSE_ALPHA_FILE           1257
#define IDC_BROWSE_MAP_FILE             1258
#define IDC_BROWSE_LIGHT_FILE           1259
#define IDC_LIST_MAP_ALTITUDE_INDEX     1260
#define IDC_BROWSE_IMAGE_FILE_NAME      1261
#define IDC_BROWSE_ALPHA_FILE_NAME      1263
#define IDC_IMAGE_ID                    1264
#define IDC_COMBO_SAMPLE_ID             1270
#define IDC_HOVER_SCRIPT                1271
#define IDC_TRIGGER_SCRIPT              1273
#define IDC_FILESET_ID                  1274
#define IDC_DESCRIPTION                 1275
#define IDC_DELETE                      1278
#define IDC_UNHOVER_SCRIPT              1280
#define IDC_CLICK_TRIGGER               1281
#define IDC_EDIT                        1283
#define IDC_ENTRANCE_SCRIPT             1285
#define IDC_EXIT_SCRIPT                 1286
#define IDC_LIST_TRACK_RECORD           1290
#define IDC_START_PLAY_TIME             1291
#define IDC_START_VOLUME_TIME           1292
#define IDC_END_VOLUME_TIME             1293
#define IDC_FRAME_EXPIRATION            1296
#define IDC_CURRENT_FRAME_CLOCK_VALUE   1298
#define IDC_COMMAND_START_TIME          1299
#define IDC_COMMAND_END_TIME            1300
#define IDC_VOLUME_START_TIME           1302
#define IDC_VOLUME_END_TIME             1303
#define IDC_STARTING_TIME               1304
#define IDC_START_CLOCK_VALUE1          1305
#define IDC_ADD                         1307
#define IDC_IS_CLOCK_POWERED            1308
#define IDC_LIST_INTERACTION            1309
#define IDC_ID                          1310
#define IDC_COMBO_SCENE_ID              1316
#define IDC_LABEL                       1317
#define IDC_LABEL2                      1318
#define IDC_CHARACTER_ID                1319
#define IDC_SPIN_RED                    1321
#define IDC_SPIN_BLUE                   1322
#define IDC_SPIN_GREEN                  1323
#define IDC_INDEX                       1324
#define IDC_HEIGHT                      1325
#define IDC_TRACK_ID                    1326
#define IDC_TRACK_VALUE                 1327
#define IDC_SPIN_X_VALUE                1328
#define IDC_SPIN_Y_VALUE                1329
#define IDC_SPIN_WIDTH                  1330
#define IDC_SPIN_HEIGHT                 1331
#define IDC_SPIN_MAP_HEIGHT             1332
#define IDC_SPIN_BACK_INIT_WIDTH        1333
#define IDC_SPIN_BACK_INIT_HEIGHT       1334
#define IDC_SPIN_BACK_INIT_X            1335
#define IDC_SPIN_BACK_INIT_Y            1336
#define IDC_SPIN_BACK_FINISH_WIDTH      1337
#define IDC_SPIN_BACK_FINISH_HEIGHT     1338
#define IDC_SPIN_BACK_FINISH_X          1339
#define IDC_SPIN_BACK_FINISH_Y          1340
#define IDC_SPIN_IMAGE_WIDTH            1341
#define IDC_SPIN_IMAGE_HEIGHT           1342
#define IDC_SPIN_IMAGE_X                1343
#define IDC_SPIN_IMAGE_Y                1344
#define IDC_SPIN_MAP_OFFSET_X           1345
#define IDC_SPIN_MAP_OFFSET_Y           1346
#define IDC_SPIN_CAMERA_ANGLE           1347
#define IDC_SPIN_CAMERA_HEIGHT          1348
#define IDC_SPIN_INIT_WIDTH             1349
#define IDC_SPIN_INIT_HEIGHT            1350
#define IDC_SPIN_INIT_X                 1351
#define IDC_SPIN_INIT_Y                 1352
#define IDC_SPIN_INIT_DIST              1353
#define IDC_SPIN_FINISH_WIDTH           1354
#define IDC_SPIN_FINISH_HEIGHT          1355
#define IDC_SPIN_FINISH_X               1356
#define IDC_SPIN_FINISH_Y               1357
#define IDC_SPIN_FINISH_DIST            1358
#define IDC_SPIN_INIT_X_VALUE           1361
#define IDC_SPIN_INIT_Y_VALUE           1363
#define IDC_SPIN_INIT_DISTANCE          1366
#define IDC_SPIN_FINAL_X_VALUE          1367
#define IDC_SPIN_FINAL_Y_VALUE          1368
#define IDC_SPIN_FINAL_WIDTH            1369
#define IDC_SPIN_FINAL_HEIGHT           1370
#define IDC_SPIN_FINAL_DISTANCE         1371
#define IDC_SPIN_X1                     1372
#define IDC_SPIN_Y1                     1373
#define IDC_SPIN_X2                     1374
#define IDC_SPIN_Y2                     1375
#define IDC_SPIN_KEY_CODE               1376
#define IDC_IS_CHARACTER_VISIBLE        1378
#define IDC_IS_CHARACTER_AFFECTED_BY_LIGHT 1379
#define IDC_SECTION_NUMBER              1380
#define IDC_NEXT_FRAME                  1382
#define IDC_TIME_OF_THE_PREVIOUS_FRAME  1383
#define IDC_TIME_OF_THE_NEXT_FRAME      1384
#define IDC_CLIP_ID                     1386
#define IDC_TRANS_X                     1387
#define IDC_TRANS_Y                     1388
#define IDC_TRANS_Z                     1389
#define IDC_TIME                        1390
#define IDC_CLIP_LIST                   1391
#define IDC_CLIP_COUNT                  1392
#define IDC_DEFAULT_CLIP                1393
#define IDC_CLIP_FILE_NAME              1394
#define IDC_COLOR_FILE                  1395
#define IDC_VERTEX_FILE                 1396
#define IDC_BROWSE_FILE_NAME            1397
#define IDC_BROWSE_COLOR_FILE           1398
#define IDC_BROWSE_VERTEX_FILE          1399
#define IDC_FIRST_FRAME                 1400
#define IDC_LAST_FRAME                  1401
#define IDC_NUM_PER_SECOND              1402
#define IDC_LOOP_COUNT                  1403
#define IDC_TYPE_ID_CMB                 1405
#define IDC_FILE_NAME_LABEL             1406
#define IDC_TYPE_ID                     1408
#define IDC_UP                          1409
#define IDC_DOWN                        1410
#define ID_NEW                          32771
#define ID_SAVE                         32772
#define ID_DELETE                       32773
#define ID_ADD_WORLD                    32774
#define ID_GET_DATA_FROM_DB             32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1411
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
