#include <dos.h>
#include <iostream.h>
#include <graphics.h>
#include <stdlib.h>
#include <stdio.h>
#include <conio.h>
void time(int,int);
int avto(int);
int manual();
int reset(int);
void buttons(int);
void poly(int ,int ,int ,int ,int ,int );
void mouse_close();
void sea_mouse();
void mouse_zero(void);
int arrow (int );
int mouse(int);
void move();
void tra_lts();
void menu();