#include<stdio.h>
main()
{
int a1,a2,a3,a4,a5,a6,a7,a8,a9,a0;
int b1,b2,b3,b4,b5,b6,b7,b8,b9,b0;
int c=30;
a1=a2=a3=a4=a5=a6=a7=a8=a9=a0=1;
b1=b2=b3=b4=b5=b6=b7=b8=b9=b0=10;
	  printf("\nllllllllllllllllll");
a1=-1&&1;b1=5||0;              printf("\n a=%d b=%d",a1,b1);
a4=(b4>5)||(b4=12);          printf("\n a=%d b=%d ",a4,b4);
a5=(b5<5)||(b5=12);          printf("\n a=%d b=%d ",a5,b5);
a6=(b6>5)&&(b6=12);          printf("\n a=%d b=%d ",a6,b6);
a7=(b7<5)&&(b7=12);          printf("\n a=%d b=%d ",a7,b7);

a4=1||(b4=12);          printf("\n a=%d b=%d ",a4,b4);
a5=0||(b5=12);          printf("\n a=%d b=%d ",a5,b5);
a6=1&&(b6=12);          printf("\n a=%d b=%d ",a6,b6);
a7=0&&(b7=12);          printf("\n a=%d b=%d ",a7,b7);
(a9=5)||(!a9)&&(b9=2);       printf("\n a=%d b=%d ",a9,b9);
}






